
package hotelmanagement;


import hotelmanagement.InvalidCVV;
 import java.io.*;
import javax.swing.JOptionPane;

public class CreditCardPayment extends javax.swing.JFrame {
User u;
   private double money;
    public CreditCardPayment() {
        initComponents();
    }
    public CreditCardPayment(CreditCard obj, User u){
        initComponents();
      money = obj.getAmount();
      this.u = u;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cardHolderLabel = new javax.swing.JLabel();
        CardHolderNameText = new javax.swing.JTextField();
        cardNumberField = new javax.swing.JTextField();
        cvvField = new javax.swing.JTextField();
        cvvLabel = new javax.swing.JLabel();
        cardNumberLabel = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        ExpiryDateLabel = new javax.swing.JLabel();
        AmericanExpressButton = new javax.swing.JRadioButton();
        VisaCardButton = new javax.swing.JRadioButton();
        MasterCardButton = new javax.swing.JRadioButton();
        CancelButton = new javax.swing.JButton();
        ContinueButton = new javax.swing.JButton();
        cardNameLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(56, 173, 169));

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Payment Details");

        cardHolderLabel.setBackground(new java.awt.Color(255, 255, 255));
        cardHolderLabel.setFont(new java.awt.Font("Segoe UI Semilight", 0, 20)); // NOI18N
        cardHolderLabel.setForeground(new java.awt.Color(255, 255, 255));
        cardHolderLabel.setText("Card Holder Name:");

        CardHolderNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CardHolderNameTextActionPerformed(evt);
            }
        });

        cardNumberField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardNumberFieldActionPerformed(evt);
            }
        });

        cvvField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cvvFieldActionPerformed(evt);
            }
        });

        cvvLabel.setFont(new java.awt.Font("Segoe UI Semilight", 0, 20)); // NOI18N
        cvvLabel.setForeground(new java.awt.Color(255, 255, 255));
        cvvLabel.setText("CVV");

        cardNumberLabel.setFont(new java.awt.Font("Segoe UI Semilight", 0, 20)); // NOI18N
        cardNumberLabel.setForeground(new java.awt.Color(255, 255, 255));
        cardNumberLabel.setText("Credit Card Number:");

        ExpiryDateLabel.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        ExpiryDateLabel.setForeground(new java.awt.Color(255, 255, 255));
        ExpiryDateLabel.setText("Expiry Date:");

        AmericanExpressButton.setBackground(new java.awt.Color(56, 173, 169));
        AmericanExpressButton.setFont(new java.awt.Font("Segoe UI Semilight", 0, 20)); // NOI18N
        AmericanExpressButton.setForeground(new java.awt.Color(255, 255, 255));
        AmericanExpressButton.setText("American Express ");
        AmericanExpressButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AmericanExpressButtonActionPerformed(evt);
            }
        });

        VisaCardButton.setBackground(new java.awt.Color(56, 173, 169));
        VisaCardButton.setFont(new java.awt.Font("Segoe UI Semilight", 0, 20)); // NOI18N
        VisaCardButton.setForeground(new java.awt.Color(255, 255, 255));
        VisaCardButton.setText("VISA");
        VisaCardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisaCardButtonActionPerformed(evt);
            }
        });

        MasterCardButton.setBackground(new java.awt.Color(56, 173, 169));
        MasterCardButton.setFont(new java.awt.Font("Segoe UI Semilight", 0, 20)); // NOI18N
        MasterCardButton.setForeground(new java.awt.Color(255, 255, 255));
        MasterCardButton.setText("Master Card");
        MasterCardButton.setIconTextGap(10);
        MasterCardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MasterCardButtonActionPerformed(evt);
            }
        });

        CancelButton.setBackground(new java.awt.Color(56, 173, 169));
        CancelButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 20)); // NOI18N
        CancelButton.setForeground(new java.awt.Color(255, 255, 255));
        CancelButton.setText("CANCEL");
        CancelButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        CancelButton.setFocusPainted(false);
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        ContinueButton.setBackground(new java.awt.Color(56, 173, 169));
        ContinueButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 20)); // NOI18N
        ContinueButton.setForeground(new java.awt.Color(255, 255, 255));
        ContinueButton.setText("CONTINUE");
        ContinueButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        ContinueButton.setFocusPainted(false);
        ContinueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContinueButtonActionPerformed(evt);
            }
        });

        cardNameLabel.setFont(new java.awt.Font("Segoe UI Semilight", 0, 20)); // NOI18N
        cardNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        cardNameLabel.setText("Card Name:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cardHolderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cardNumberLabel)
                            .addComponent(ExpiryDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cardNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(ContinueButton, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(85, 85, 85)
                                .addComponent(CancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CardHolderNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(AmericanExpressButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(MasterCardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(VisaCardButton))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(27, 27, 27)
                                            .addComponent(cvvLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(cvvField))
                                        .addComponent(cardNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(jLabel3)))
                .addContainerGap(170, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cardHolderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CardHolderNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cardNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ExpiryDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cvvField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cvvLabel))
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AmericanExpressButton)
                    .addComponent(VisaCardButton)
                    .addComponent(MasterCardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ContinueButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(459, 459, 459)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(262, 262, 262)
                .addComponent(jLabel4))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CardHolderNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CardHolderNameTextActionPerformed
 
    }//GEN-LAST:event_CardHolderNameTextActionPerformed

    private void cvvFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cvvFieldActionPerformed

    }//GEN-LAST:event_cvvFieldActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        this.hide();
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void ContinueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContinueButtonActionPerformed
      try{
        File file = new File("creditCards.txt");
        FileWriter ff = new FileWriter(file, true);
        BufferedWriter bw = new BufferedWriter(ff);
        if ( VisaCardButton.isSelected() && cardNumberField.getText().matches("^4[0-9]{12}(?:[0-9]{3})?$") ){

             
                
                    bw.write(u.getCustomerID().toString() + "  " + cardNumberField.getText() + "  " + "Room tariff total:" + "  " + money);
                    bw.newLine(); bw.close(); ff.close();
                PaymentSuccessful ps = new PaymentSuccessful(u);
               ps.setVisible(true);}
               
            
           
        
      
        
        else if ( MasterCardButton.isSelected() && cardNumberField.getText().matches("^(?:5[1-5][0-9]{2}|222[1-9]|22[3-9][0-9]|2[3-6][0-9]{2}|27[01][0-9]|2720)[0-9]{12}$") ){
                
             
                
                    bw.write(u.getCustomerID() + "  " + cardNumberField.getText() + "  " + "Room tariff total:" + "  " + money);
                    bw.newLine(); bw.close(); ff.close();
               PaymentSuccessful ps = new PaymentSuccessful(u);
               ps.setVisible(true);
            
             
        
      }
        else if ( AmericanExpressButton.isSelected() && cardNumberField.getText().matches("^3[47][0-9]{13}$") ){
                     
          
             
               
                    bw.write(u.getCustomerID() + "  " + cardNumberField.getText() + "  " + "Room tariff total:" + "  " + money);
                    bw.newLine(); bw.close(); ff.close();
                    PaymentSuccessful ps = new PaymentSuccessful(u);
               ps.setVisible(true);
               ps.setLocationRelativeTo(null);
            
         
        }
        else {
                 
               CreditCardDetailsError cd = new CreditCardDetailsError();
               cd.setVisible(true);
        }    
        
    }
    catch(Exception b ) {
    System.out.println(b);
        
}
    }//GEN-LAST:event_ContinueButtonActionPerformed

    private void cardNumberFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardNumberFieldActionPerformed

                
    }//GEN-LAST:event_cardNumberFieldActionPerformed

    private void MasterCardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MasterCardButtonActionPerformed
        if(MasterCardButton.isSelected()){
          VisaCardButton.setSelected(false);
          AmericanExpressButton.setSelected(false);
        }
    }//GEN-LAST:event_MasterCardButtonActionPerformed

    private void VisaCardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisaCardButtonActionPerformed
        if(VisaCardButton.isSelected()){
          AmericanExpressButton.setSelected(false);
          MasterCardButton.setSelected(false);
        }
    }//GEN-LAST:event_VisaCardButtonActionPerformed

    private void AmericanExpressButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AmericanExpressButtonActionPerformed
       if(AmericanExpressButton.isSelected()){
          VisaCardButton.setSelected(false);
          MasterCardButton.setSelected(false);
       }
    }//GEN-LAST:event_AmericanExpressButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreditCardPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreditCardPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreditCardPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreditCardPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreditCardPayment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton AmericanExpressButton;
    private javax.swing.JButton CancelButton;
    private javax.swing.JTextField CardHolderNameText;
    private javax.swing.JButton ContinueButton;
    private javax.swing.JLabel ExpiryDateLabel;
    private javax.swing.JRadioButton MasterCardButton;
    private javax.swing.JRadioButton VisaCardButton;
    private javax.swing.JLabel cardHolderLabel;
    private javax.swing.JLabel cardNameLabel;
    private javax.swing.JTextField cardNumberField;
    private javax.swing.JLabel cardNumberLabel;
    private javax.swing.JTextField cvvField;
    private javax.swing.JLabel cvvLabel;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
