/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelmanagement;

import hotelmanagement.Services;
import hotelmanagement.ServicesTotal;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;

/**
 *
 * @author Maryam
 */
public class ServiceForm extends javax.swing.JFrame {

    /**
     * Creates new form ServiceForm
     */
    User u;
    Services s;
   
    public ServiceForm() {
        initComponents();
    }
    
    
    
    public ServiceForm(User u) {
       initComponents();
        this.u = u;
        s = new Services(u);
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        DineInButton = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        PoolButton = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        cartButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        ResetButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        RoomServiceButton = new javax.swing.JCheckBox();
        ClubButton = new javax.swing.JCheckBox();
        FoodOrderingButton = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(56, 173, 169));

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Services");

        jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Note that these are free for Members only.");

        jLabel10.setFont(new java.awt.Font("Segoe UI Semilight", 0, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("          Prices");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jLabel1)))
                .addContainerGap(216, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(135, 135, 135))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(372, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(600, 600));
        setPreferredSize(new java.awt.Dimension(1200, 1200));

        jPanel2.setBackground(new java.awt.Color(56, 173, 169));
        jPanel2.setMaximumSize(new java.awt.Dimension(600, 600));
        jPanel2.setMinimumSize(new java.awt.Dimension(600, 600));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Price (in €)");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(724, 162, 89, 27);

        DineInButton.setBackground(new java.awt.Color(56, 173, 169));
        DineInButton.setFont(new java.awt.Font("Segoe UI Semilight", 0, 20)); // NOI18N
        DineInButton.setForeground(new java.awt.Color(255, 255, 255));
        DineInButton.setText("Dine-in");
        DineInButton.setFocusPainted(false);
        DineInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DineInButtonActionPerformed(evt);
            }
        });
        jPanel2.add(DineInButton);
        DineInButton.setBounds(270, 240, 100, 29);

        jLabel11.setFont(new java.awt.Font("Segoe UI Light", 0, 48)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Services");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(454, 57, 160, 64);

        PoolButton.setBackground(new java.awt.Color(56, 173, 169));
        PoolButton.setFont(new java.awt.Font("Segoe UI Semilight", 0, 20)); // NOI18N
        PoolButton.setForeground(new java.awt.Color(255, 255, 255));
        PoolButton.setText("Pool ");
        PoolButton.setFocusPainted(false);
        PoolButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PoolButtonActionPerformed(evt);
            }
        });
        jPanel2.add(PoolButton);
        PoolButton.setBounds(270, 280, 74, 35);

        jLabel5.setFont(new java.awt.Font("Segoe UI Semilight", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("2000");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(745, 204, 80, 27);

        cartButton.setBackground(new java.awt.Color(56, 173, 169));
        cartButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 20)); // NOI18N
        cartButton.setForeground(new java.awt.Color(255, 255, 255));
        cartButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelmanagement/icons8-plus-50.png"))); // NOI18N
        cartButton.setText("ADD TO CART");
        cartButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        cartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cartButtonActionPerformed(evt);
            }
        });
        jPanel2.add(cartButton);
        cartButton.setBounds(140, 520, 230, 64);

        CancelButton.setBackground(new java.awt.Color(56, 173, 169));
        CancelButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 20)); // NOI18N
        CancelButton.setForeground(new java.awt.Color(255, 255, 255));
        CancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelmanagement/icons8-go-back-50.png"))); // NOI18N
        CancelButton.setText("BACK");
        CancelButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });
        jPanel2.add(CancelButton);
        CancelButton.setBounds(740, 520, 198, 64);

        ResetButton.setBackground(new java.awt.Color(56, 173, 169));
        ResetButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 20)); // NOI18N
        ResetButton.setForeground(new java.awt.Color(255, 255, 255));
        ResetButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelmanagement/icons8-synchronize-50.png"))); // NOI18N
        ResetButton.setText("RESET");
        ResetButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        ResetButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetButtonActionPerformed(evt);
            }
        });
        jPanel2.add(ResetButton);
        ResetButton.setBounds(460, 520, 190, 61);

        jLabel8.setFont(new java.awt.Font("Segoe UI Semilight", 0, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("6000");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(740, 320, 70, 27);

        jLabel9.setFont(new java.awt.Font("Segoe UI Semilight", 0, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("500");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(750, 370, 70, 27);

        jLabel6.setFont(new java.awt.Font("Segoe UI Semilight", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("5000");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(740, 240, 80, 27);

        jLabel7.setFont(new java.awt.Font("Segoe UI Semilight", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("5500");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(740, 280, 70, 27);

        RoomServiceButton.setBackground(new java.awt.Color(56, 173, 169));
        RoomServiceButton.setFont(new java.awt.Font("Segoe UI Semilight", 0, 20)); // NOI18N
        RoomServiceButton.setForeground(new java.awt.Color(255, 255, 255));
        RoomServiceButton.setText("Room Service");
        RoomServiceButton.setFocusPainted(false);
        RoomServiceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoomServiceButtonActionPerformed(evt);
            }
        });
        jPanel2.add(RoomServiceButton);
        RoomServiceButton.setBounds(270, 200, 150, 35);

        ClubButton.setBackground(new java.awt.Color(56, 173, 169));
        ClubButton.setFont(new java.awt.Font("Segoe UI Semilight", 0, 20)); // NOI18N
        ClubButton.setForeground(new java.awt.Color(255, 255, 255));
        ClubButton.setText("Club");
        ClubButton.setFocusPainted(false);
        ClubButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClubButtonActionPerformed(evt);
            }
        });
        jPanel2.add(ClubButton);
        ClubButton.setBounds(270, 320, 70, 35);

        FoodOrderingButton.setBackground(new java.awt.Color(56, 173, 169));
        FoodOrderingButton.setFont(new java.awt.Font("Segoe UI Semilight", 0, 20)); // NOI18N
        FoodOrderingButton.setForeground(new java.awt.Color(255, 255, 255));
        FoodOrderingButton.setText("Food Ordering");
        FoodOrderingButton.setFocusPainted(false);
        FoodOrderingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FoodOrderingButtonActionPerformed(evt);
            }
        });
        jPanel2.add(FoodOrderingButton);
        FoodOrderingButton.setBounds(270, 360, 156, 35);

        jLabel4.setFont(new java.awt.Font("Segoe UI Semilight", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Service");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(280, 160, 137, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PoolButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PoolButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PoolButtonActionPerformed

    private void RoomServiceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoomServiceButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RoomServiceButtonActionPerformed

    private void ResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetButtonActionPerformed
       PoolButton.setSelected(false);
       RoomServiceButton.setSelected(false);
       DineInButton.setSelected(false);
       ClubButton.setSelected(false);
       FoodOrderingButton.setSelected(false);
       
    }//GEN-LAST:event_ResetButtonActionPerformed

    private void cartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cartButtonActionPerformed

     if(PoolButton.isSelected())
      s.AvailPool();
    if(ClubButton.isSelected())
      s.AvailClub();
    if(DineInButton.isSelected())
       s.AvailDineIn();
    if(FoodOrderingButton.isSelected())
       s.AvailFoodOrdering();
    if(RoomServiceButton.isSelected())
       s.AvailRoomService();
   

    try{
    FileWriter f = new FileWriter(new File("hotelServices.txt"), true);
    BufferedWriter bb = new BufferedWriter(f);
    bb.write("Customer ID: "); // find a way to get Member object involved here somewhere
    bb.newLine();
    bb.write(s.getServicesAvailed());
    bb.newLine();
    bb.write("***********");}
    catch (Exception e){
        System.out.println(e);
    }
    
 
    
    ServicesTotal st = new ServicesTotal(s);
   
    st.setVisible(true);
    st.setLocationRelativeTo(null);
    this.hide();
    
    }//GEN-LAST:event_cartButtonActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void DineInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DineInButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DineInButtonActionPerformed

    private void ClubButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClubButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClubButtonActionPerformed

    private void FoodOrderingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FoodOrderingButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FoodOrderingButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServiceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServiceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServiceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServiceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServiceForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton;
    private javax.swing.JCheckBox ClubButton;
    private javax.swing.JCheckBox DineInButton;
    private javax.swing.JCheckBox FoodOrderingButton;
    private javax.swing.JCheckBox PoolButton;
    private javax.swing.JButton ResetButton;
    private javax.swing.JCheckBox RoomServiceButton;
    private javax.swing.JButton cartButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
